In [1]:
import pandas as pd
import json

In [2]:
from pathlib import Path

ROOT = Path().resolve().parent
RAW_DATA = ROOT / "data" / "raw"
INTERIM_DATA = ROOT / "data" / "interim"

In [ ]:
with open(Path(RAW_DATA / "the_analyst.json"), encoding="utf-8") as f:
    data = json.load(f)


player_data = data["player"]
groups = ["attack", "possession", "carries", "defending", "goalkeeping"]
dfs = {}

for key in player_data.keys():
    if key in groups:
        for category, df in player_data[key].items():
            dfs[f"{key}_{category}"] = pd.DataFrame(df)

In [4]:
dfs.keys()

dict_keys(['attack_overall', 'attack_nonPenalty', 'possession_chanceCreation', 'possession_passing', 'carries_overall', 'defending_overall', 'defending_discipline', 'goalkeeping_overall'])

In [5]:
dfs["attack_overall"].columns

Index(['player_id', 'apps', 'mins_played', 'goals', 'xg', 'goals_vs_xg',
       'shots', 'shots_on_target', 'shot_conv', 'xg_per_shot', 'player',
       'first_name', 'last_name', 'date_of_birth', 'age', 'team_id',
       'shirt_number', 'squad_position', 'squad_position_detailed',
       'player_uuid', 'team_uuid', 'contestantName', 'contestantClubName',
       'contestantShortName', 'contestantCode'],
      dtype='str')

In [6]:
dfs["attack_nonPenalty"].columns

Index(['player_id', 'apps', 'mins_played', 'np_goals', 'np_xg',
       'np_goals_vs_xg', 'np_shots', 'np_shots_on_target', 'np_shot_conv',
       'np_xg_per_shot', 'player', 'first_name', 'last_name', 'date_of_birth',
       'age', 'team_id', 'shirt_number', 'squad_position',
       'squad_position_detailed', 'player_uuid', 'team_uuid', 'contestantName',
       'contestantClubName', 'contestantShortName', 'contestantCode'],
      dtype='str')

In [7]:
comm_cols_to_del = list(set(dfs["attack_overall"].columns).intersection(set(dfs["attack_nonPenalty"].columns)))

In [8]:
comm_cols_to_del.pop(comm_cols_to_del.index("player_id"))

'player_id'

In [9]:
comm_cols_to_del

['first_name',
 'age',
 'apps',
 'contestantCode',
 'date_of_birth',
 'contestantClubName',
 'shirt_number',
 'squad_position_detailed',
 'contestantName',
 'player_uuid',
 'team_id',
 'squad_position',
 'contestantShortName',
 'team_uuid',
 'mins_played',
 'last_name',
 'player']

In [10]:
attack_nonPenalty = dfs["attack_nonPenalty"].drop(columns=comm_cols_to_del)

In [11]:
attack_df = pd.merge(dfs["attack_overall"], attack_nonPenalty, on="player_id")

In [12]:
final_col_to_del = [
    "first_name",
    "last_name",
    "date_of_birth",
    "age",
    "team_id",
    "shirt_number",
    "player_uuid",
    "team_uuid",
    "contestantName",
    "contestantShortName",
    "contestantCode",
]

In [13]:
attack_df = attack_df.drop(columns=final_col_to_del)

In [14]:
attack_df

,player_id,apps,mins_played,goals,xg,goals_vs_xg,shots,shots_on_target,shot_conv,xg_per_shot,...,squad_position,squad_position_detailed,contestantClubName,np_goals,np_xg,np_goals_vs_xg,np_shots,np_shots_on_target,np_shot_conv,np_xg_per_shot
0,184341,23,1018,3,1.50,1.50,19,5,15.79,0.08,...,Midfielder,Attacking Midfielder,Manchester United,3,1.50,1.50,19,5,15.79,0.08
1,592031,34,2398,3,3.80,-0.80,41,11,7.32,0.09,...,Forward,Winger,Brighton & Hove Albion,3,3.80,-0.80,41,11,7.32,0.09
2,606745,17,923,0,0.35,-0.35,3,0,0.00,0.12,...,Defender,Full Back,Manchester United,0,0.35,-0.35,3,0,0.00,0.12
3,469142,36,3211,3,3.30,-0.30,23,10,13.04,0.14,...,Defender,Central Defender,Brighton & Hove Albion,3,3.30,-0.30,23,10,13.04,0.14
4,60307,19,1636,1,1.45,-0.45,18,9,5.56,0.08,...,Midfielder,Central Midfielder,Brighton & Hove Albion,1,1.45,-0.45,18,9,5.56,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,469247,0,0,0,0.00,0.00,0,0,0.00,0.00,...,Forward,Winger,Aston Villa,0,0.00,0.00,0,0,0.00,0.00
601,623110,0,0,0,0.00,0.00,0,0,0.00,0.00,...,Forward,Winger,Newcastle United,0,0.00,0.00,0,0,0.00,0.00
602,606775,1,6,0,0.00,0.00,0,0,0.00,0.00,...,Midfielder,0,AFC Bournemouth,0,0.00,0.00,0,0,0.00,0.00
603,424044,1,16,0,0.00,0.00,0,0,0.00,0.00,...,Midfielder,Attacking Midfielder,AFC Bournemouth,0,0.00,0.00,0,0,0.00,0.00
604,168991,0,0,0,0.00,0.00,0,0,0.00,0.00,...,Midfielder,Defensive Midfielder,AFC Bournemouth,0,0.00,0.00,0,0,0.00,0.00

In [15]:
dfs["possession_chanceCreation"]

,player_id,mins_played,apps,chances_created,op_chances_created,chances_per_100_pass,chances_sp_op_ratio,xa,op_xa,assists,...,team_id,shirt_number,squad_position,squad_position_detailed,player_uuid,team_uuid,contestantName,contestantClubName,contestantShortName,contestantCode
0,184341,1018,23,13,12,2.82,7.69,1.622,1.468,0,...,1,7,Midfielder,Attacking Midfielder,8nh6qf9i1d0qw7nx4wk25qzth,6eqit8ye8aomdsrrq0hk3v7gh,Manchester United FC,Manchester United,Man Utd,MUN
1,592031,2398,34,44,35,5.66,11.36,5.122,4.922,4,...,36,11,Forward,Winger,50lnmkk33eoivv4ksly77hkpg,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
2,606745,923,17,2,1,0.22,0.00,0.183,0.183,1,...,1,26,Defender,Full Back,4tb2hobv1dwon0e8djvuohxxw,6eqit8ye8aomdsrrq0hk3v7gh,Manchester United FC,Manchester United,Man Utd,MUN
3,469142,3211,36,13,10,0.41,0.00,1.616,1.611,3,...,36,6,Defender,Central Defender,2gj7h5fxuh4y0tbp6j308yk4q,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
4,60307,1636,19,39,24,2.36,30.77,3.831,2.919,3,...,36,30,Midfielder,Central Midfielder,3k6znit6fd9mbfcnphlwyvj6d,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,469247,0,0,0,0,0.00,0.00,0.000,0.000,0,...,7,19,Forward,Winger,469247,b496gs285it6bheuikox6z9mj,Aston Villa FC,Aston Villa,Aston Villa,AVL
601,623110,0,0,0,0,0.00,0.00,0.000,0.000,0,...,4,64,Forward,Winger,623110,7vn2i2kd35zuetw6b38gw9jsz,Newcastle United FC,Newcastle United,Newcastle,NEW
602,606775,6,1,0,0,0.00,0.00,0.000,0.000,0,...,91,47,Midfielder,0,a27jmusots4qlgmc8yrecv02c,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU
603,424044,16,1,1,0,0.00,0.00,0.000,0.000,1,...,91,25,Midfielder,Attacking Midfielder,ctq9si3nbc6n8cznhlcvtixd6,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU
604,168991,0,0,0,0,0.00,0.00,0.000,0.000,0,...,91,29,Midfielder,Defensive Midfielder,168991,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU

In [16]:
possession_passing = dfs["possession_passing"].drop(columns=comm_cols_to_del)

In [17]:
possesion_df = pd.merge(dfs["possession_chanceCreation"], possession_passing, on="player_id")

In [18]:
possesion_df = possesion_df.drop(columns=final_col_to_del)

In [19]:
carries_df = dfs["carries_overall"].drop(columns=comm_cols_to_del)

In [20]:
carries_df.columns

Index(['player_id', 'carries', 'carry_distance', 'progressive_carries',
       'progressive_distance', 'shot_ending', 'goal_ending', 'chance_ending',
       'assist_ending', 'dist_per_carry', 'dist_per_progressive_carry'],
      dtype='str')

In [21]:
dfs.keys()

dict_keys(['attack_overall', 'attack_nonPenalty', 'possession_chanceCreation', 'possession_passing', 'carries_overall', 'defending_overall', 'defending_discipline', 'goalkeeping_overall'])

In [22]:
dfs["defending_overall"]

,player_id,mins_played,apps,tackles,interceptions,recoveries,blocks,clearances,ground_duels,ground_duels_won,...,team_id,shirt_number,squad_position,squad_position_detailed,player_uuid,team_uuid,contestantName,contestantClubName,contestantShortName,contestantCode
0,184341,1018,23,24,9,60,1,9,94,43,...,1,7,Midfielder,Attacking Midfielder,8nh6qf9i1d0qw7nx4wk25qzth,6eqit8ye8aomdsrrq0hk3v7gh,Manchester United FC,Manchester United,Man Utd,MUN
1,592031,2398,34,56,17,95,0,16,285,143,...,36,11,Forward,Winger,50lnmkk33eoivv4ksly77hkpg,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
2,606745,923,17,22,1,40,11,60,52,37,...,1,26,Defender,Full Back,4tb2hobv1dwon0e8djvuohxxw,6eqit8ye8aomdsrrq0hk3v7gh,Manchester United FC,Manchester United,Man Utd,MUN
3,469142,3211,36,53,47,113,28,189,148,95,...,36,6,Defender,Central Defender,2gj7h5fxuh4y0tbp6j308yk4q,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
4,60307,1636,19,29,12,76,4,24,101,48,...,36,30,Midfielder,Central Midfielder,3k6znit6fd9mbfcnphlwyvj6d,e5p0ehyguld7egzhiedpdnc3w,Brighton & Hove Albion FC,Brighton & Hove Albion,Brighton,BHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,469247,0,0,0,0,0,0,0,0,0,...,7,19,Forward,Winger,469247,b496gs285it6bheuikox6z9mj,Aston Villa FC,Aston Villa,Aston Villa,AVL
601,623110,0,0,0,0,0,0,0,0,0,...,4,64,Forward,Winger,623110,7vn2i2kd35zuetw6b38gw9jsz,Newcastle United FC,Newcastle United,Newcastle,NEW
602,606775,6,1,0,0,0,0,0,0,0,...,91,47,Midfielder,0,a27jmusots4qlgmc8yrecv02c,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU
603,424044,16,1,1,0,2,0,1,2,1,...,91,25,Midfielder,Attacking Midfielder,ctq9si3nbc6n8cznhlcvtixd6,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU
604,168991,0,0,0,0,0,0,0,0,0,...,91,29,Midfielder,Defensive Midfielder,168991,1pse9ta7a45pi2w2grjim70ge,AFC Bournemouth,AFC Bournemouth,Bournemouth,BOU

In [23]:
defending_discipline = dfs["defending_discipline"].drop(columns=comm_cols_to_del)

In [24]:
defending_df = pd.merge(dfs["defending_overall"], defending_discipline, on="player_id")

In [25]:
defending_df = defending_df.drop(columns=final_col_to_del)

In [26]:
final_col_to_del

['first_name',
 'last_name',
 'date_of_birth',
 'age',
 'team_id',
 'shirt_number',
 'player_uuid',
 'team_uuid',
 'contestantName',
 'contestantShortName',
 'contestantCode']

In [27]:
goalkeeping_col_to_del = final_col_to_del.copy()

In [28]:
goalkeeping_col_to_del.append("squad_position_detailed")

In [29]:
goalkeeping_df = dfs["goalkeeping_overall"].drop(columns=goalkeeping_col_to_del)

In [30]:
goalkeeping_df

,player_id,apps,mins_played,team_mins,team_mins_perc,ogs,goals_conceded,saves_made,save_perc,goals_prevented,goals_prevented_rate,xgot_conceded,player,squad_position,contestantClubName
0,200720,37,3330,3420,97,2,49,110,69.18,1.83,1.02,48.83,Caoimhín Kelleher,Goalkeeper,Brentford
1,204936,34,3060,3420,89,0,29,78,72.90,5.66,1.17,34.66,Gianluigi Donnarumma,Goalkeeper,Manchester City
2,172649,37,3330,3420,97,2,51,106,67.52,3.31,1.06,52.31,Dean Henderson,Goalkeeper,Crystal Palace
3,432720,4,360,3420,11,0,6,14,70.00,2.53,1.33,8.53,James Trafford,Goalkeeper,Manchester City
4,88248,3,270,3420,8,0,4,8,66.67,1.15,1.25,5.15,Stefan Ortega,Goalkeeper,Nottingham Forest
5,449027,10,868,3420,25,0,18,34,65.38,-2.62,0.83,15.38,Giorgi Mamardashvili,Goalkeeper,Liverpool
6,518030,3,270,3420,8,0,4,10,71.43,1.60,1.25,5.60,Max Weiss,Goalkeeper,Burnley
7,515046,3,270,3420,8,0,2,10,83.33,0.61,1.00,2.61,Melker Ellborg,Goalkeeper,Sunderland
8,84182,20,1800,3420,53,1,37,77,67.54,-0.49,0.97,35.51,Alphonse Areola,Goalkeeper,West Ham United
9,98980,32,2835,3420,83,0,39,95,70.90,3.10,1.08,42.10,Emiliano Martínez,Goalkeeper,Aston Villa
10,72147,7,585,3420,17,1,10,19,65.52,0.62,1.00,9.62,Marco Bizot,Goalkeeper,Aston Villa
11,109745,1,90,3420,3,0,1,2,66.67,-0.05,0.00,0.95,Kepa Arrizabalaga,Goalkeeper,Arsenal
12,121709,1,90,3420,3,0,0,3,100.00,0.33,0.00,0.33,Walter Benítez,Goalkeeper,Crystal Palace
13,111234,38,3420,3420,100,1,50,100,66.67,3.64,1.06,52.64,Jordan Pickford,Goalkeeper,Everton
14,155503,3,212,3420,6,0,4,9,69.23,-0.28,0.75,3.72,Freddie Woodman,Goalkeeper,Liverpool
15,489639,38,3420,3420,100,4,46,106,69.74,5.48,1.12,47.48,Bart Verbruggen,Goalkeeper,Brighton & Hove Albion
16,79602,3,270,3420,8,0,7,7,50.00,0.15,1.00,7.15,Dan Bentley,Goalkeeper,Wolverhampton Wanderers
17,465247,32,2880,3420,84,2,39,79,66.95,6.49,1.16,43.49,Senne Lammens,Goalkeeper,Manchester United
18,451302,6,540,3420,16,0,11,13,54.17,-0.71,0.91,10.29,Altay Bayindir,Goalkeeper,Manchester United
19,225321,12,1003,3420,29,1,17,25,59.52,0.69,1.00,16.69,Aaron Ramsdale,Goalkeeper,Newcastle United
20,215059,35,3041,3420,89,1,47,98,67.59,2.67,1.04,48.67,Robert Sánchez,Goalkeeper,Chelsea
21,508479,5,378,3420,11,0,5,8,61.54,-2.62,0.40,2.38,Filip Jörgensen,Goalkeeper,Chelsea
22,85633,31,2667,3420,78,3,39,95,70.90,3.61,1.08,39.61,Matz Sels,Goalkeeper,Nottingham Forest
23,485055,7,630,3420,18,0,7,10,58.82,-0.54,0.86,6.46,Antonín Kinsky,Goalkeeper,Tottenham Hotspur
24,507433,1,90,3420,3,1,3,1,25.00,-0.84,0.50,1.16,Hákon Valdimarsson,Goalkeeper,Brentford
25,154561,37,3330,3420,97,1,26,60,69.77,-0.66,0.96,24.34,David Raya,Goalkeeper,Arsenal
26,59735,22,1980,3420,58,1,27,63,70.00,-0.58,0.96,25.42,Karl Darlow,Goalkeeper,Leeds United
27,221389,5,438,3420,13,0,8,6,42.86,-2.80,0.62,5.20,John Victor,Goalkeeper,Nottingham Forest
28,498016,35,3150,3420,92,2,46,109,70.32,-0.01,0.98,43.99,Robin Roefs,Goalkeeper,Sunderland
29,98747,27,2417,3420,71,1,38,89,70.08,-2.00,0.95,35.00,Nick Pope,Goalkeeper,Newcastle United
30,201595,16,1440,3420,42,0,29,38,56.72,-2.51,0.90,26.49,Lucas Perri,Goalkeeper,Leeds United
31,149065,23,2070,3420,61,0,37,65,63.73,-3.06,0.89,33.94,José Sá,Goalkeeper,Wolverhampton Wanderers
32,67089,35,3150,3420,92,4,71,127,64.14,0.71,1.00,67.71,Martin Dúbravka,Goalkeeper,Burnley
33,116535,26,2340,3420,68,0,31,57,64.77,-3.31,0.87,27.69,Alisson Becker,Goalkeeper,Liverpool
34,80201,38,3420,3420,100,3,51,98,65.77,-2.56,0.94,45.44,Bernd Leno,Goalkeeper,Fulham
35,457569,38,3420,3420,100,3,54,109,66.87,0.60,1.00,51.60,Djordje Petrovic,Goalkeeper,AFC Bournemouth
36,467189,18,1620,3420,47,2,28,55,66.27,-3.13,0.85,22.87,Mads Hermansen,Goalkeeper,West Ham United
37,101982,12,1080,3420,32,4,24,39,61.90,-1.57,0.90,18.43,Sam Johnstone,Goalkeeper,Wolverhampton Wanderers
38,184254,31,2790,3420,82,0,50,83,62.41,-5.54,0.88,44.46,Guglielmo Vicario,Goalkeeper,Tottenham Hotspur

In [48]:
goalkeeping_df.drop(columns="player_id").to_parquet(INTERIM_DATA / "the_analyst_gk.parquet")

In [32]:
the_analyst_df = attack_df.copy()

In [33]:
the_analyst_df = pd.merge(the_analyst_df, carries_df, on="player_id")

In [34]:
set(the_analyst_df.columns).intersection(set(defending_df.columns))

{'apps',
 'contestantClubName',
 'mins_played',
 'player',
 'player_id',
 'squad_position',
 'squad_position_detailed'}

In [35]:
master_def_common = list(set(the_analyst_df.columns).intersection(set(defending_df.columns)))
master_def_common.pop(master_def_common.index("player_id"))

'player_id'

In [36]:
defending_df = defending_df.drop(columns=master_def_common)

In [37]:
the_analyst_df = pd.merge(the_analyst_df, defending_df, on="player_id")

In [38]:
the_analyst_df

,player_id,apps,mins_played,goals,xg,goals_vs_xg,shots,shots_on_target,shot_conv,xg_per_shot,...,ground_duels_won,ground_duel_perc,aerial_duels,aerial_duels_won,aerial_duel_perc,yellows,reds,fouls_commited,pens_conceded,offsides
0,184341,23,1018,3,1.50,1.50,19,5,15.79,0.08,...,43,45.745,21,7,33.333,2,0,16,0,0
1,592031,34,2398,3,3.80,-0.80,41,11,7.32,0.09,...,143,50.175,51,19,37.255,3,0,32,0,10
2,606745,17,923,0,0.35,-0.35,3,0,0.00,0.12,...,37,71.154,28,18,64.286,2,0,7,0,0
3,469142,36,3211,3,3.30,-0.30,23,10,13.04,0.14,...,95,64.189,194,114,58.763,9,0,27,1,4
4,60307,19,1636,1,1.45,-0.45,18,9,5.56,0.08,...,48,47.525,30,13,43.333,2,0,17,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,469247,0,0,0,0.00,0.00,0,0,0.00,0.00,...,0,0.000,0,0,0.000,0,0,0,0,0
601,623110,0,0,0,0.00,0.00,0,0,0.00,0.00,...,0,0.000,0,0,0.000,0,0,0,0,0
602,606775,1,6,0,0.00,0.00,0,0,0.00,0.00,...,0,0.000,1,0,0.000,0,0,0,0,0
603,424044,1,16,0,0.00,0.00,0,0,0.00,0.00,...,1,50.000,2,0,0.000,0,0,0,0,0
604,168991,0,0,0,0.00,0.00,0,0,0.00,0.00,...,0,0.000,0,0,0.000,0,0,0,0,0

In [39]:
master_possesion_df = list(set(the_analyst_df.columns).intersection(set(possesion_df.columns)))
master_possesion_df.pop(master_possesion_df.index("player_id"))

'player_id'

In [40]:
possesion_df = possesion_df.drop(columns=master_possesion_df)

In [41]:
the_analyst_df = pd.merge(the_analyst_df, possesion_df, on="player_id")

In [42]:
the_analyst_df.columns

Index(['player_id', 'apps', 'mins_played', 'goals', 'xg', 'goals_vs_xg',
       'shots', 'shots_on_target', 'shot_conv', 'xg_per_shot', 'player',
       'squad_position', 'squad_position_detailed', 'contestantClubName',
       'np_goals', 'np_xg', 'np_goals_vs_xg', 'np_shots', 'np_shots_on_target',
       'np_shot_conv', 'np_xg_per_shot', 'carries', 'carry_distance',
       'progressive_carries', 'progressive_distance', 'shot_ending',
       'goal_ending', 'chance_ending', 'assist_ending', 'dist_per_carry',
       'dist_per_progressive_carry', 'tackles', 'interceptions', 'recoveries',
       'blocks', 'clearances', 'ground_duels', 'ground_duels_won',
       'ground_duel_perc', 'aerial_duels', 'aerial_duels_won',
       'aerial_duel_perc', 'yellows', 'reds', 'fouls_commited',
       'pens_conceded', 'offsides', 'chances_created', 'op_chances_created',
       'chances_per_100_pass', 'chances_sp_op_ratio', 'xa', 'op_xa', 'assists',
       'op_assists', 'passes', 'successful_passes', 'pass_perc',
       'total_final_third_passes', 'successful_final_third_passes',
       'ft_pass_perc', 'op_crosses', 'successful_op_crosses', 'cross_perc',
       'through_balls', 'successful_through_balls', 'through_ball_perc'],
      dtype='str')

In [43]:
the_analyst_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 67 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   player_id                      605 non-null    int64
 1   apps                           605 non-null    int64
 2   mins_played                    605 non-null    int64
 3   goals                          605 non-null    int64
 4   xg                             605 non-null    float64
 5   goals_vs_xg                    605 non-null    float64
 6   shots                          605 non-null    int64
 7   shots_on_target                605 non-null    int64
 8   shot_conv                      605 non-null    float64
 9   xg_per_shot                    605 non-null    float64
 10  player                         605 non-null    str
 11  squad_position                 605 non-null    str
 12  squad_position_detailed        605 non-null    object
 13  contestantClubName             605 non-null    str
 14  np_goals                       605 non-null    int64
 15  np_xg                          605 non-null    float64
 16  np_goals_vs_xg                 605 non-null    float64
 17  np_shots                       605 non-null    int64
 18  np_shots_on_target             605 non-null    int64
 19  np_shot_conv                   605 non-null    float64
 20  np_xg_per_shot                 605 non-null    float64
 21  carries                        605 non-null    int64
 22  carry_distance                 605 non-null    float64
 23  progressive_carries            605 non-null    int64
 24  progressive_distance           605 non-null    float64
 25  shot_ending                    605 non-null    int64
 26  goal_ending                    605 non-null    int64
 27  chance_ending                  605 non-null    int64
 28  assist_ending                  605 non-null    int64
 29  dist_per_carry                 605 non-null    float64
 30  dist_per_progressive_carry     605 non-null    float64
 31  tackles                        605 non-null    int64
 32  interceptions                  605 non-null    int64
 33  recoveries                     605 non-null    int64
 34  blocks                         605 non-null    int64
 35  clearances                     605 non-null    int64
 36  ground_duels                   605 non-null    int64
 37  ground_duels_won               605 non-null    int64
 38  ground_duel_perc               605 non-null    float64
 39  aerial_duels                   605 non-null    int64
 40  aerial_duels_won               605 non-null    int64
 41  aerial_duel_perc               605 non-null    float64
 42  yellows                        605 non-null    int64
 43  reds                           605 non-null    int64
 44  fouls_commited                 605 non-null    int64
 45  pens_conceded                  605 non-null    int64
 46  offsides                       605 non-null    int64
 47  chances_created                605 non-null    int64
 48  op_chances_created             605 non-null    int64
 49  chances_per_100_pass           605 non-null    float64
 50  chances_sp_op_ratio            605 non-null    float64
 51  xa                             605 non-null    float64
 52  op_xa                          605 non-null    float64
 53  assists                        605 non-null    int64
 54  op_assists                     605 non-null    int64
 55  passes                         605 non-null    int64
 56  successful_passes              605 non-null    int64
 57  pass_perc                      605 non-null    float64
 58  total_final_third_passes       605 non-null    int64
 59  successful_final_third_passes  605 non-null    int64
 60  ft_pass_perc                   605 non-null    float64
 61  op_crosses                     605 non-null    int64
 62  successful_op_crosses          605 non-null    int64
 63  cross_perc                     605 non-null    float64
 64  through_balls                  605 non-null    int64
 65  successful_through_balls       605 non-null    int64
 66  through_ball_perc              605 non-null    float64
dtypes: float64(22), int64(41), object(1), str(3)
memory usage: 337.3+ KB

In [44]:
the_analyst_df.select_dtypes(include=["object"], exclude=["string"])

    squad_position_detailed
0      Attacking Midfielder
1                    Winger
2                 Full Back
3          Central Defender
4        Central Midfielder
..                      ...
600                  Winger
601                  Winger
602                       0
603    Attacking Midfielder
604    Defensive Midfielder

[605 rows x 1 columns]

In [45]:
the_analyst_df["squad_position_detailed"] = the_analyst_df["squad_position_detailed"].astype("str")

In [49]:
the_analyst_df = the_analyst_df.drop(columns="player_id")

In [54]:
the_analyst_df = the_analyst_df[the_analyst_df["mins_played"] != 0]

In [55]:
the_analyst_df

,apps,mins_played,goals,xg,goals_vs_xg,shots,shots_on_target,shot_conv,xg_per_shot,player,...,pass_perc,total_final_third_passes,successful_final_third_passes,ft_pass_perc,op_crosses,successful_op_crosses,cross_perc,through_balls,successful_through_balls,through_ball_perc
0,23,1018,3,1.50,1.50,19,5,15.79,0.08,Mason Mount,...,81.59,180,146,81.11,13,0,0.00,7,4,57.14
1,34,2398,3,3.80,-0.80,41,11,7.32,0.09,Yankuba Minteh,...,67.94,332,206,62.05,134,31,23.13,2,1,50.00
2,17,923,0,0.35,-0.35,3,0,0.00,0.12,Ayden Heaven,...,90.49,46,33,71.74,1,0,0.00,1,0,0.00
3,36,3211,3,3.30,-0.30,23,10,13.04,0.14,Jan Paul van Hecke,...,87.19,499,333,66.73,23,10,43.48,1,0,0.00
4,19,1636,1,1.45,-0.45,18,9,5.56,0.08,Pascal Groß,...,85.93,364,268,73.63,56,21,37.50,2,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,1,2,0,0.00,0.00,0,0,0.00,0.00,Odsonne Édouard,...,0.00,0,0,0.00,0,0,0.00,0,0,0.00
593,2,180,0,0.10,-0.10,2,0,0.00,0.05,Nayef Aguerd,...,90.43,21,17,80.95,2,0,0.00,0,0,0.00
596,1,11,0,0.00,0.00,0,0,0.00,0.00,Jota Silva,...,100.00,1,1,100.00,1,0,0.00,0,0,0.00
602,1,6,0,0.00,0.00,0,0,0.00,0.00,Ben Winterburn,...,0.00,1,0,0.00,0,0,0.00,0,0,0.00
603,1,16,0,0.00,0.00,0,0,0.00,0.00,Hamed Traoré,...,100.00,0,0,0.00,0,0,0.00,0,0,0.00

In [56]:
the_analyst_df.to_parquet(INTERIM_DATA / "the_analyst_player.parquet")